name: CI

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install Theos
        uses: Randomblock1/theos-action@v1.4

      - name: Build package
        run: |
          rm -f packages/*
          make package FINALPACKAGE=1

      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: "Package built by ${{ matrix.os }}"
          path: ${{ github.workspace }}/packages/*.deb
