name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Theos
      run: |
        sudo apt-get update
        sudo apt-get install -y autoconf bash curl openssl
        bash -c "$(curl -fsSL "https://raw.githubusercontent.com/theos/theos/master/bin/install-theos")"

    - name: Set THEOS_MAKE_PATH
      run: echo "THEOS_MAKE_PATH set to ${THEOS}/makefiles"
      env:
        THEOS: /path/to/theos

    - name: Build the tweak
      run: make package
